### ISSUE TITLE
Audio truncation of various sounds

### ISSUE THREAD

**Issue by jake-b** [pguyot/Einstein#18] opened 2017-01-21 02:03 UTC
I've been looking into why the startup chime and other sounds get truncated.  I haven't figured it out yet.  So far, it seems like Einstein's the audio driver does not receive anything past 25600 bytes.  I've confirmed this with the TCoreAudioSoundManager and a custom SoundManger class that logs the audio frames to disk.

Note that the issue doesn't occur only on boot-up.  If you use NewtTest and play the boot up sound, it will truncate there as well.

Still poking but no progress yet.

**Comment by FrankFromPdaSoft** [comment] 2017-01-21 03:20
Matthias and me have been tinkering with this some time ago. I do not clearly recall the details, but I dimly remember that at least under Android the Newton’s intention to play sound is sampled in an Android loop, which is not the best way to do things. Android checks in a loop if the Newton wants to put out sound and, if it does, forwards it to the Android sound system. The problem is, I think, that Newton sound chunks are limited in size, so there is often more than one chunk to play in very close succession. Sound chunks should be forwarded to Android immediately when the Newton asks for it, not when the loop checks the next time. Because when this happens, the Newton might have already finished playing, and chunks will fall through the gap. It would be better if the Newton emulation could ask Android to put out sound immediately.

 

As I said, this is for Android, and it was a long time ago. But I wouldn’t be surprised if things were similar for the other platforms.

 

Or some such. It’s four in the morning over here and hence far too late to think J

 

Von: jake-b [mailto:notifications@github.com] 
Gesendet: Samstag, 21. Januar 2017 03:04
An: pguyot/Einstein
Cc: Subscribed
Betreff: [pguyot/Einstein] Audio truncation of various sounds (#18)

 

I've been looking into why the startup chime and other sounds get truncated. I haven't figured it out yet. So far, it seems like Einstein's the audio driver does not receive anything past 25600 bytes. I've confirmed this with the TCoreAudioSoundManager and a custom SoundManger class that logs the audio frames to disk.

Note that the issue doesn't occur only on boot-up. If you use NewtTest and play the boot up sound, it will truncate there as well.

Still poking but no progress yet.

**Comment by pguyot** [comment] 2017-01-21 07:05
Interesting. It was so slow back in 2007 that I assumed it was caused by emulator speed, and therefore I always used the null sound driver.

Indeed, the REX driver only gets 25600 bytes as chunks of 0xEA0 bytes (the actual size of each buffers) followed by a last chunk of 0xC40 bytes. I guess the problem isn't in host code but rather that the driver isn't responding what NewtonOS expects.

With @panicsteve excellent new monitor, it should be fixable.

**Comment by jake-b** [comment] 2017-01-21 11:55
I'm poking around the disassembly and looking at `PCirrusSoundDriver::ScheduleOutputBuffer(unsigned long, unsigned long)`

 It seems that it calls  `PCirrusSoundDriver::SyncVolume(unsigned char)` and `PCirrusSoundDriver::SyncOutputBits(void)`

Might be a problem where the SyncOutputBits part of some acknowledgement to NewtonOS that its okay to send the next bit.

**Comment by panicsteve** [comment] 2017-01-23 16:26
I don't have any insight to add to this.  But I wanted to add that sometimes sound _loops_ also.  Possibly more on iOS than on desktop platforms.  I'm not sure if that's caused by the same bug, but it might be.  It possibly supports the theory that it's not audio frames getting lost, but some sort of signaling problem between Einstein and the emulated Newton.

**Comment by pguyot** [comment] 2017-01-23 16:33
From what I have seen, I also believe it's a signaling problem. The emulator might be consuming sound data too fast and a solution could be to implement something closer to the original sound driver with two buffers only (instead of an infinite circle buffer as we currently have) and only signal whenever a buffer is depleted (I guess that's what NewtonOS expects). Also, I think if NewtonOS schedules buffer 0 with a size of 0, sound should stop. Apparently, MacOS X renders sound by chunks smaller than NewtonOS sound buffers, so it should be doable.

**Comment by jake-b** [comment] 2017-01-23 17:28
I did a quick test at lunch and yes, it seems that if you delay raising the interrupt to request more data until you've consumed most of the ring buffer then it works.  Still have the audio looping issue.  More playing to do when I can find the time.

**Comment by MatthiasWM** [comment] 2017-01-23 21:31
> On Jan 23, 2017, at 6:28 PM, jake-b <notifications@github.com> wrote:
> 
> I did a quick test at lunch and yes, it seems that if you delay raising the interrupt to request more data until you've consumed most of the ring buffer then it works. Still have the audio looping issue. More playing to do when I can find the time.

That makes a lot of sense. It seems that the OS simply assumes that some time passes (a number of timing interrupts is called) before the next buffer needs to be ready. This is IMHO very similar to what we see when using the serial port with fast machines. The OS simply assumes that there is enough time to prepare the next block of data before the actual request arrives. Remember "slowdown.exe" :-) ? 

The looping issue, hmm, maybe we are missing a flag that needs to be set in the DMA hardware register bank?

**Comment by jake-b** [comment] 2017-01-23 21:42
There are two bugs here.  One is the truncation issue, and one is the looping issue.

The truncation issue is as Paul states, we're consuming the data too quickly, or raising the interrupt too often.  A fix is to NOT raise the interrupt when you're receiving data from NewtonOS in ScheduleOutput.  Instead, only request new data when you need it on the consumer site, in the CoreAudio callback.

The second bug may be a bug in the ring buffer implementation, where its possible that the producer and consumer pointers jump each other and then replay data in the buffer repeatedly until things line up again.  I didn't go into the TCircleBuffer to debug it specifically, but putting a MIN() operation before the consume seems to prevent the issue.

Here is a patch with the two changes.  I would appreciate some more eyes on it before it gets committed.

https://gist.github.com/jake-b/085c1976ba578f6a5ec60a720d6594cc

**Comment by panicsteve** [comment] 2017-01-23 23:03
I applied your patch to my working copy and I can hear the full boot sound now on my Mac.  Tapped around a variety of things, ran some sound tests in NewtTest -- not very scientific, but no problems found.

This is probably harmless, but in RenderCallback(), since the mDataMutex->Lock() has been removed before mOutputBuffer->Consume(), the corresponding mDataMutex->Unlock() should probably also be removed.

**Comment by panicsteve** [comment] 2017-01-23 23:05
Actually, on second look, did you intend to remove that mutex lock or not?

**Comment by jake-b** [comment] 2017-01-23 23:19
I did not.  Thanks for the catch.

**Comment by jake-b** [comment] 2017-01-23 23:38
I fixed the missing mutex lock and checked it in.  Probably still need to figure out why the ring buffer goes wonky sometimes, but the MIN() operation prevents the consumption of too many bytes.

**Comment by panicsteve** [comment] 2017-01-24 01:40
Would it be worthwhile to pull the ring buffer class out into a separate, standalone project for testing purposes, and hit it with a variety of scenarios (overrun, underrun, etc) to see if it does the right thing?

**Comment by jake-b** [comment] 2017-01-24 01:50
Yeah.  I was thinking of adding a few test cases to the test suite, not that it's an area of the code that is oft-changing.

**Comment by pguyot** [comment] 2017-01-24 08:02
TCircleBuffer is only used with sound and it can be trashed in favor of a dual buffer solution which is what NewtonOS actually expects.

**Comment by codepoet80** [comment] 2017-01-28 14:19
Am I the only one that gets sounds playing really slowly and drawn out? Start-up chime and tap chirp are fine, but drawer's opening sounds like a dying paper shredder...

**Comment by jake-b** [comment] 2017-01-28 14:56
On iOS the audio callback seems to exhaust the buffer too quickly.  Seems like a difference in behavior between MacOS and iOS.  I'll look into it.

**Comment by jake-b** [comment] 2017-01-28 16:02
A release build with fast optimizations seems to work on my big iPad Pro.  Might just be a case that the debug build is too slow to feed the buffer.

**Comment by INDIGI-CO-UK** [comment] 2017-11-30 22:56
Today I have build Einstein for High Sierra. The sound glitch showed up again. Einstein don't play startup sound to the end.

**Comment by chuma** [comment] 2018-04-11 15:32
I've been mucking around in the sound code for the past few weeks, after finding that the PortAudio sound output on Linux was glitchy.  I tried to fix PortAudio but ended up writing a new PulseAudio output driver for the emulator and submitted a pull request for it.

In the PulseAudio driver, I ended up skipping the ring buffer entirely and set up the PulseAudio buffers so that I just copied the Newton's buffers straight in whenever `ScheduleOutput()` is called.  This probably works due to the fact that:

* PulseAudio has a thread-based API available
* It can handle audio in non-host endianness
* Instead of waiting for PulseAudio's output callback, you can prepare a PulseAudio buffer and write to it whenever you are ready

One thing that I wasn't that clear on exactly when to call `RaiseOutputInterrupt()` - but it works.

**Comment by chuma** [comment] 2018-04-12 17:41
> Today I have build Einstein for High Sierra. The sound glitch showed up again. Einstein don't play startup sound to the end.

Weird.  My Mac is still on Sierra, and I built Einstein a few weeks ago from the head of the master branch, and sound was perfect.  In fact that's what I used to capture the startup sound (https://marc.info/?l=newtontalk&m=152225142131418&w=2)

@INDIGI-CO-UK did you build from the most recent sources?  Sound was definitely broken on the 2017.1.0 tag but was fixed shortly afterwards.

**Comment by MatthiasWM** [comment] 2018-05-12 14:01
The sound works great on MacOS High Sierra. How is the Linux version coming along? How about MSWindows? Android? iOS? Can we close this?

**Comment by chuma** [comment] 2018-05-17 16:25
IMHO, this can be closed, as I could not reproduce any sound issues on OS X, and on Linux, PulseAudio is working great.

**Comment by MatthiasWM** [comment] 2018-05-18 07:56
Closed as resolved.

**Closed by MatthiasWM** 2018-05-18 07:56 UTC
Labels: bug
