### ISSUE TITLE
FTLK UI not visible on macOS Big Sur with M1-based mac

### ISSUE THREAD

**Issue by soapdog** [pguyot/Einstein#97] opened 2021-03-15 12:49 UTC
## Basic Information

* Platform (Mac, iOS, Android, Linux, etc): macOS Big Sur
* Built from source? (yes/no): 
    * If yes, source branch/revision ID: 
    * If no, release version: 2020.4.13

## Description of issue

The FTLK UI is not visible. Widgets will become visible if their rect is clicked and in some cases on hover.

## Expected behaviour

The UI should be visible.

## Steps to reproduce issue

Just launching the app and trying to use it.

## Screenshots

https://user-images.githubusercontent.com/23247/111155814-dc210800-858c-11eb-9b14-9f79732f8885.mp4

**Comment by panicsteve** [comment] 2021-03-15 16:38
Can confirm this happens with the FLTK build on _both_ M1 and Intel running Big Sur.  Native UI version not affected.

Not familiar enough with FLTK to diagnose.  Maybe it's not using the normal macOS runloop.

**Comment by MatthiasWM** [comment] 2021-03-15 19:08
Upgrading my Mac as we speak... . I will take a look at that.

**Comment by MatthiasWM** [comment] 2021-03-15 21:29
OK, I can repeat the problem. That's a good thing. The issue is the same on Intel machines. Thanks btw for the great description including video!

**Comment by MatthiasWM** [comment] 2021-03-15 22:37
OK, this is a known issue with FLTK when building for older MacOS systems (I included 10.9 Mavericks). It is fixed now. There are now two FLTK versions fro MacOS:

http://www.messagepad.org/Newton_Installs.html#macOS

Also updated build instructions.

**Closed by MatthiasWM** 2021-03-15 22:37 UTC
