### ISSUE TITLE
Hanging on ROM Boot on OS X 10.11.x

### ISSUE THREAD

**Issue by morgant** [pguyot/Einstein#13] opened 2016-12-13 11:43 UTC
I built Einstein from a fresh clone of master on OS X 10.11.6 with Xcode 7.3.1, restored my old `~/Library/Application Support/Einstein Platform/` folder & prefs, but Einstein hangs at 2% of "Booting... ROM Boot". I see the following in `/var/log/system.log`:

```
Dec 13 06:22:07 host tccd[523]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:07 host tccd[523]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:07 --- last message repeated 1 time ---
Dec 13 06:22:07 host launchservicesd[75]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:08 --- last message repeated 1 time ---
Dec 13 06:22:08 host coreaudiod[143]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:08 host appleeventsd[49]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:08 hostsharedfilelistd[520]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:12 host launchservicesd[75]: SecTaskLoadEntitlements failed error=22
Dec 13 06:22:43 --- last message repeated 1 time ---
```

After a few minutes:

```
Dec 13 06:23:39 host kernel[0]: process Einstein[18507] thread 634774 caught burning CPU! It used more than 50% CPU (Actual recent usage: 98%) over 180 seconds. thread lifetime cpu usage 90.094707 seconds, (89.387735 user, 0.706972 system) ledger info: balance: 90006195249 credit: 90006195249 debit: 0 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 91832129582 
Dec 13 06:23:39 host com.apple.xpc.launchd[1] (com.apple.ReportCrash[18511]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
Dec 13 06:23:39 host ReportCrash[18511]: Invoking spindump for pid=18507 thread=634774 percent_cpu=98 duration=92 because of excessive cpu utilization
Dec 13 06:23:43 host spindump[221]: Saved cpu_resource.diag report for Einstein version ??? (2012.9) to /Library/Logs/DiagnosticReports/Einstein_2016-12-13-062343_host.cpu_resource.diag
```

I have tried trashing my prefs (knowing they were from a much older version), as well as trashing the `newton.rom.img` (leaving just the `newton.rom` file). I believe this ROM was generated from my MP2100, but it has been years.

**Comment by panicsteve** [comment] 2016-12-13 19:29
It sounds like the virtual Newton might be getting stuck in a reboot loop.  My guess it's either something about the format of the ROM image, or an incompatibility with something else in that old Einstein Platform folder.

First thing I'd try is to move _everything_ out of the Einstein Platform folder except the newton.rom and try again.  If it still fails, you may need a different ROM image, as I think the "2%" marker is about where ROM patching and injections happen.

**Comment by morgant** [comment] 2016-12-14 00:44
@panicsteve Thanks, I've now tried clearing out the `internal.flash` file as well (the only other thing in that folder), to no avail. My `newton.rom` is 8388608 bytes, so that's good...

Aha! If I run it from Xcode (build for "Running"), it boots completely, but hangs at 2% if I launch the version I exported as a Mac app (without signing). As this is a dev box, I have "Allow apps from anywhere" enabled. Is there something else from OS X 10.11 El Capitan that's coming into play?

Thanks for the assistance!

**Comment by MatthiasWM** [comment] 2016-12-17 17:37
It has this nasty bug for many years now, The OS X version gets stuck at 2% in 20% of new installations when using a fully optimized compilation of Einstein. Launching again sometimes help. Clearing all caches often helps, but not always. I have put many hours into this, but Einstein compiled in debug mode does not exhibit this behavior. The Monitor does not help either, and because the lockup is random, I can't even repeat it for the optimized version in a reliable way.

Since clearing all caches usually fixed the issue, I gave up eventually. I'd love to see what the actual issue is. Maybe a deadlock in the thread system depending on very tight timing? Things like these are incredibly hard to debug :-(

**Comment by panicsteve** [comment] 2016-12-17 21:26
I don't think it's a deadlock because the logs say the process is consuming high CPU.  So, I think it's getting in a tight loop somewhere (possibly a Newton reboot loop).  @morgant It might be worth turning on debug symbols for the Release build, and performing a sample on the process while it's spinning, to see where it is.  My guess would be in the bowels of the ARM code, but we can check.

**Comment by INDIGI-CO-UK** [comment] 2016-12-17 22:46
Guys, I'm sorry for OT, but can I ask you kindly for help with install Einstein on Zaurus SL-5500? I'm total noob. I don't know how to even start with this. Is there any system image file to just copy on Zaurus, or something like this?

Thank you,
Pawel

**Comment by morgant** [comment] 2016-12-18 04:00
@panicsteve Thanks, I'll give that a shot and let you know what I find.

@pawel Probably best to start a new issue for that topic. I wanted to try that setup when Paul et al first got it working!

**Comment by MatthiasWM** [comment] 2016-12-20 19:49
This bug has been around for many years. Clearing the directory and trying again usually fixes things for the next attempt and from then on - but not in all cases.

I have tried to find the bug using the Monitor and common debugging (which is a major PITA when running inside a JIT Compiler), but in either case, the bug seems to disappear.

My guess is that we run into some deadlock, maybe within the threads, but again, I could never repeat this in debug mode.

On 13. Dezember 2016 20:29:42 MEZ, Steven Frank <notifications@github.com> wrote:
>It sounds like the virtual Newton might be getting stuck in a reboot
>loop.  My guess it's either something about the format of the ROM
>image, or an incompatibility with something else in that old Einstein
>Platform folder.
>
>First thing I'd try is to move _everything_ out of the Einstein
>Platform folder except the newton.rom and try again.  If it still
>fails, you may need a different ROM image, as I think the "2%" marker
>is about where ROM patching and injections happen.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pguyot/Einstein/issues/13#issuecomment-266837129

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.
-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by MatthiasWM** [comment] 2016-12-20 19:49
This bug has been around for many years. Clearing the directory and trying again usually fixes things for the next attempt and from then on - but not in all cases.

I have tried to find the bug using the Monitor and common debugging (which is a major PITA when running inside a JIT Compiler), but in either case, the bug seems to disappear.

My guess is that we run into some deadlock, maybe within the threads, but again, I could never repeat this in debug mode.

On 13. Dezember 2016 20:29:42 MEZ, Steven Frank <notifications@github.com> wrote:
>It sounds like the virtual Newton might be getting stuck in a reboot
>loop.  My guess it's either something about the format of the ROM
>image, or an incompatibility with something else in that old Einstein
>Platform folder.
>
>First thing I'd try is to move _everything_ out of the Einstein
>Platform folder except the newton.rom and try again.  If it still
>fails, you may need a different ROM image, as I think the "2%" marker
>is about where ROM patching and injections happen.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pguyot/Einstein/issues/13#issuecomment-266837129

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by panicsteve** [comment] 2017-01-17 21:52
I can confirm Matthias's observation that this seems to have something to do with compiler optimization.

If I set the optimization levels to "None" for Distribution and Release configurations (shown in green in the attached screenshot), then the Release build does not hang.  At the default setting for these configurations ("Fastest, Smallest") the hang is reproducible.

![screen shot 2017-01-17 at 1 36 48 pm](https://cloud.githubusercontent.com/assets/196190/22041247/f9588922-dcba-11e6-955d-443600f777ce.png)

It turns out the "2%" overlay message is shown when the emulated Newton's CPU reaches address 0x00018688 ("ROMBoot") which it usually does after the first instruction runs.  (The first instruction in ROM is simply a branch to this address.)  So, there's no great significance to this message other than we can confirm the emulator reached at least this point.

The process continues to run at a high CPU load, so it seems like the emulator is trying to do something, but getting stuck in a reset loop (I'm hypothesizing here).  As Matthias said, quite tricky to debug!

**Comment by panicsteve** [comment] 2017-01-17 22:32
I have a possible fix for this!

I noticed the static analyzer was generating a lot of warnings for the use of an uninitialized variable.  There were two main instances of this:

- LDM1_Template(FLAG_P, FLAG_U, FLAG_W, Rn) in Emulator/JIT/Generic/TJITGeneric_LDM1_Template.h
- STM1_Template(FLAG_P, FLAG_U, FLAG_W, Rn) in Emulator/JIT/Generic/TJITGeneric_STM1_Template.h

In both functions, there's a variable called theAddress which is not initialized.

Furthermore, if the code follows the path where (curRegList & 1) is true and isFirst is false, then the uninitialized value will be used to determine which Newton memory address to read or write to, which is really bad news!

It is probably a fluke that it works at all in the Debug build.  My theory is that it the previous value of the variable is sticking around in memory.  So, I figured I'd make this explicit by declaring theAddress as static, and initializing it to 0.

After making that change in those two files, both the Debug and Release builds are successfully booting the Newton for me!

I would like to know if one of you could confirm this by pulling this latest change and seeing if it also fixes the issue for you.

**Comment by panicsteve** [comment] 2017-01-18 00:20
Wow, I was wondering if this would also fix the problem I was having getting Einstein to boot on my Raspberry Pi 3, and it totally did!

http://stevenf.com/gfx/einstein-pi-2.jpg

http://stevenf.com/gfx/einstein-pi-3.jpg

**Comment by MatthiasWM** [comment] 2017-01-18 00:22
Great find, Steven. This is definitely a bug. The fix though is IMHO to move the declaration of 'theAddress' to the line before the 'while' loop. No need to make it static (which makes it slower and wastes memory because the macros implement those functions many times).

It works in debug mode because 'theAddress' is stored on the stack and remains the same during execution. In Release mode, 'theAddress' is likely stored in a register which is overwritten during the execution of other code in the loop.

The implementation optimizes access to memory by writing multiple words in a single burst instead of going through the memory manager for every word we want to write. LDM2 and LDM3 are not optimized that way and don't have this bug. STM1 does have it, STM2 does not.

Fixed it. Please verify.

**Comment by MatthiasWM** [comment] 2017-01-18 00:22
> On Jan 18, 2017, at 1:20 AM, Steven Frank <notifications@github.com> wrote:
> 
> Wow, I was wondering if this would also fix the problem I was having getting Einstein to boot on my Raspberry Pi 3, and it totally did!
> 
> http://stevenf.com/gfx/einstein-pi-2.jpg
> 
> http://stevenf.com/gfx/einstein-pi-3.jpg


Wheeee! Again, thanks so much for finding this!

**Comment by panicsteve** [comment] 2017-01-18 00:48
Picked up your change, and confirmed it still works on Mac Release builds.  I think we can call this one closed!  Nice!

**Closed by panicsteve** 2017-01-18 00:48 UTC

**Comment by splorp** [comment] 2017-01-18 04:03
Rawk. Nice work, gents.

**Comment by pguyot** [comment] 2017-01-18 05:17
Excellent!

**Comment by morgant** [comment] 2017-01-19 21:11
@panicsteve Thanks for the hard work and the fix! Just recompiled & archived and it works great!

**Comment by gingerbeardman** [comment] 2023-12-29 22:47
Not sure if this is related but my gut says it is: Binary Release v2022.4.20 hangs on "Booting..." for me (macOS 12.7.2, M1 Pro) but my own build runs fine. Cheers!
